       IDENTIFICATION DIVISION.
       PROGRAM-ID. CHAPTER-40.
       DATA DIVISION.
       FILE SECTION.
       WORKING-STORAGE SECTION.
       77 NumberValue PIC 9.
       PROCEDURE DIVISION.
       MAIN-PROCEDURE.

            STOP RUN.
       END PROGRAM CHAPTER-40.
